### ISSUE TITLE
Build fails due to outdated build.zig file with zig v0.13.0-dev.xxx

### ISSUE THREAD

**Issue by rokibhasansagar** [dnjulek/vapoursynth-ssimulacra2#2]
The error is as follows:
`/home/runner/work/vapoursynth-ssimulacra2/vapoursynth-ssimulacra2/build.zig:12:33: error: no field named 'path' in union 'Build.LazyPath'`

Maybe the below line needs fix after the update to `v0.13.0-dev.xxx` release, as it is in https://github.com/dnjulek/vapoursynth-zig/commit/5c469881298ed13c073eb3a3b262f506bca55270#diff-4936d00eff537930259b875e33d907aa717b8c999c448c582bd4e3ea77655fb8R12 ?
https://github.com/dnjulek/vapoursynth-ssimulacra2/blob/ebe175a3b3cec6c0653d50f787d491768c4b8f16/build.zig#L12

**Comment by dnjulek** [comment]
Yes, will be fixed to zig-0.13 later. 
Current version should use zig-0.12

**Comment by SuspiciousDuck** [comment]
It's been 8 months, is there any update on this?

**Comment by dnjulek** [comment]
@SuspiciousDuck Yes, the project has been moved: 
https://github.com/dnjulek/vapoursynth-zip
